export default {
  GRAY: "gray",
  PRIMARY: "#FF6F61",
  SECONDARY: "#FFD166",
  WHITE: "white",
  BLACK: "black",
  RED: "red",
  GREEN: "green",
  BLUE: "blue",
  YELLOW: "yellow",
  ORANGE: "orange",
  PURPLE: "purple",
  PINK: "pink",
  BROWN: "brown",
  GRAY_DARK: "#333",
  GRAY_LIGHT: "#ccc",
  GRAY_LIGHTER: "#eee",
  GRAY_LIGHTER2: "#f4f4f4",
  GRAY_LIGHTER3: "#f8f8f8",
};
